# GitHub Pages config

title: tsl-apple-cloudkit
description: TypeScript library for Apple CloudKit JS v2
author: © TypeScriptLibs

email: bug@typescriptlibs.org
github_username: typescriptlibs
rss: rss

show_excerpts: false

github:
  private: true

header_pages:
  - www/downloads.md
  - SECURITY.md
  - LICENSE.md
  - www/all-libraries.md

include:
  - LICENSE.md
  - README.md
  - SECURITY.md
  - www/all-libraries.md
  - www/downoads.md

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-titles-from-headings

theme: minima

minima:
  date_format: "%Y-%m-%d"
  skin: classic

titles_from_headings:
  enabled: true
  strip_title: true
  collections: true
