blank_issues_enabled: false
contact_links:
  - name: Report an issue with CloudKit JS
    url: https://developer.apple.com/bug-reporting/
    about: |
      Report a bug or submit a feature request to Apple using this link.
  - name: GitHub discussions
    url: https://github.com/orgs/typescriptlibs/discussions
    about: |
      Does the issue involve a lot of systems, or are you not sure how the issue
      is related to CloudKit JS? Consider starting a discussion first.
  - name: CloudKit JS documentation
    url: https://developer.apple.com/documentation/cloudkitjs
    about: |
      This library is just TypeScript sugar for CloudKit JS. Take a look at
      Apple's documentation for details around CloudKit.
  - name: Help with code
    url: https://stackoverflow.com/questions/tagged/cloudkit
    about: |
      If you are stuck and need help with code, StackOverflow is a great
      resource.
