title: Apple CloudKit TypeScript Library
description: CloudKit JS v2 Library for TypeScript
author: © TypeScriptLibs
email: bug@typescriptlibs.org
github_username:  typescriptlibs
rss: rss

show_excerpts: false

github:
    private: true

header_pages:
 - title: See all packages
   url: https://typescriptlibs.org/

plugins:
 - jekyll-feed
 - jekyll-seo-tag

theme: minima

minima:
  date_format: "%Y-%m-%d"
